### ISSUE TITLE
Benchmark can be misleading

### ISSUE THREAD

**Issue by fedebenelli** [m3g/2021_FortranCon#2]
I was surprised with the results in the benchmark of Fortran vs Julia (I was expecting similar performance but with a little advantage of Fortran over Julia), so I've decided to rerun the benchmarks with different optimization levels:

```sh
gfortran -O0 -march=native particle_simulation.f90 -o particle_simulation
echo "Fortran -O0:"
time ./particle_simulation

gfortran -O1 -march=native particle_simulation.f90 -o particle_simulation
echo "Fortran -O1:"
time ./particle_simulation

gfortran -O2 -march=native particle_simulation.f90 -o particle_simulation
echo "Fortran -O2:"
time ./particle_simulation

gfortran -O3 -march=native particle_simulation.f90 -o particle_simulation
echo "Fortran -O3:"
time ./particle_simulation

gfortran -Ofast -march=native particle_simulation.f90 -o particle_simulation
echo "Fortran -Ofast:"
time ./particle_simulation

echo "Julia:"
time julia particle_simulation.jl
```  

With the results:

```
Fortran -O0:
real	1m10,165s
user	1m10,128s
sys	0m0,003s

Fortran -O1:
real	0m40,524s
user	0m40,497s
sys	0m0,000s

Fortran -O2:
real	0m36,427s
user	0m36,383s
sys	0m0,017s

Fortran -O3:
real	0m39,488s
user	0m39,443s
sys	0m0,007s

Fortran -Ofast:
real	0m36,217s
user	0m36,184s
sys	0m0,007s

Julia:
real	0m38,021s
user	0m37,924s
sys	0m0,073s
```

While I know that the intent of this simple benchmark is more something in the order of "Julia speed is comparable to Fortran", I think that the results can mislead the reader into thinking that Julia is faster than Fortran. (The difference is marginal anyways, so if the user is more productive with Julia I wouldn't say that a switch is necessary just based on speed)

Honestly I don't know exactly why, but the "best" optimization algorithm (-O3) ain't necessarily the best, as it can be shown with this implementation. This also shows that there is an extra step to take into account with compiled languages, and that's that compiling flags can make a huge impact in the result, giving another layer of complexity of Fortran over Julia.

**Comment by lmiq** [comment]
This is what I get in my machine:

```
Julia:

real	0m21,660s
user	0m20,660s
sys	0m0,640s
Fortran -O0:

real	0m46,441s
user	0m46,436s
sys	0m0,004s
Fortran -O1:

real	0m29,395s
user	0m29,390s
sys	0m0,004s
Fortran -O2:

real	0m26,589s
user	0m26,589s
sys	0m0,000s
Fortran -O3:

real	0m30,221s
user	0m30,221s
sys	0m0,000s
Fortran -Ofast:

real	0m29,668s
user	0m29,666s
sys	0m0,000s
```
And actually in the case of Julia compilation time is being measured, if one excludes Julia startup time, package loading and compilation (which would be insignificant for longer simulations), we get:

```
 17.339121 seconds (182.13 k allocations: 21.264 MiB, 0.06% gc time)
```

(you can get that result by modifying the julia script at the end, adding `@time main()` after the call to `main()`. 

I'm running that on Julia 1.7.3 and gfortran 9.4.0.

I don't know where these differences come from, and I'm pretty sure it is possible to tune one or other code to get them similar in speed, but it is not expected in general that a Fortran cod should be faster than a Julia code (or vice-versa), for any fundamental reason.

**Comment by fedebenelli** [comment]
Interesting, that's a huge difference.
I've added intel's Fortran compiler, where I get a noticeable difference between both gfortran and Julia. (I've timed the Julia code with `@time main()` )

My specs are:
- gfortran: 12.1.1
- ifort: ifort (IFORT) 2021.5.0 20211109
- Julia: 1.7.3
- CPU: Intel i3-8100 (4) @ 3.600GHz
```

gfortran -Ofast:
real	0m35,581s
user	0m35,560s
sys	0m0,004s

ifort -Ofast:
real	0m19,825s
user	0m19,795s
sys	0m0,020s

Julia:
 36.656455 seconds (182.13 k allocations: 21.264 MiB)
```

**Comment by lmiq** [comment]
Note that using `-Ofast` is not really good to compare, because then you are allowing `ffastmath` operations that can be faster but have less accuracy and other guarantees. You can add `@fastmath` macros in the Julia code to get some of that, but I prefer to not use those flags anywhere. 

You may want to try as a final comparison this:

```
julia --math-mode=fast --check-bounds=no particle_simulation.jl
```

(i get 15.825851 seconds for the Julia code here).

`ifort` is probably being able to vectorize some of the calculation that julia and gfortran are not, in your machine. 

my CPU here is this one: CPU0: 11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz

Anyway, I have quite a bit of experience comparing Fortran and Julia codes by now, and I can almost guarantee that every time it is possible to tune or or the other code such that their performances are very similar. Sometimes it is easier with Julia, sometimes with Fortran. But by no means the ultimate performance of a code should be *the* defining criteria for choosing one or the other.

Saludos :-).

**Comment by fedebenelli** [comment]
```
gfortran -Ofast:
real	0m24.822s
user	0m24.812s
sys	0m0.004s

ifort -Ofast:
real	0m10.088s
user	0m10.047s
sys	0m0.030s

Julia:
real	0m14.141s
user	0m14.062s
sys	0m0.073s
```

Indeed there was a change! I've learned a couple things with this, and with respect to:

> But by no means the ultimate performance of a code should be the defining criteria for choosing one or the other.

I couldn't agree more! Maybe it sounded that I was hardly defending Fortran (well, maybe a bit), but I too consider that performance shouldn't be the reason to select a language. Productivity is key, in my opinion.

Thanks for the messages!

Saludos from Argentina! I'll be on Campinas in October, hope I meet some from your group there! (Closing issue since it wasn't really an issue)
